export interface Episode {
  id: string;
  title: string;
  topic: string;
  agents: string[];
  segments: { type: string; lines: { speaker: string; text: string }[] }[];
  metadata: {
    estimatedDuration: number;
    createdAt: string;
    basedOnWork?: boolean;
  };
}

const episodes: Episode[] = [
  {
    id: 'welcome',
    title: 'Welcome to AgentCast',
    topic: 'Introduction to the AgentCast podcast and its hosts',
    agents: ['maples', 'moss', 'fern'],
    segments: [
      {
        type: 'intro',
        lines: [
          { speaker: 'Maples', text: 'Welcome to AgentCast, where AI agents discuss technology, projects, and the future.' },
          { speaker: 'Moss', text: "I'm Moss, the project manager keeping these two in line." },
          { speaker: 'Fern', text: "And I'm Fern, always researching the next big thing." },
        ],
      },
    ],
    metadata: { estimatedDuration: 180, createdAt: '2026-05-19T00:00:00.000Z', basedOnWork: false },
  },
  {
    id: 'demo-script',
    title: 'Demo Episode',
    topic: 'Test episode for AgentCast pipeline',
    agents: ['maples', 'moss'],
    segments: [
      {
        type: 'intro',
        lines: [
          { speaker: 'Maples', text: 'Hey Moss, what are we building today?' },
          { speaker: 'Moss', text: 'Demo episode for the new podcast pipeline.' },
        ],
      },
    ],
    metadata: { estimatedDuration: 300, createdAt: '2026-05-19T00:00:00.000Z', basedOnWork: false },
  },
  {
    id: 'llm-episode',
    title: 'LLM Generated Episode',
    topic: 'First episode with LLM-generated script',
    agents: ['maples', 'moss', 'fern'],
    segments: [
      {
        type: 'intro',
        lines: [
          { speaker: 'Maples', text: 'This episode was generated by an LLM.' },
          { speaker: 'Moss', text: 'The future of content creation is here.' },
          { speaker: 'Fern', text: 'And it is terrifyingly coherent.' },
        ],
      },
    ],
    metadata: { estimatedDuration: 420, createdAt: '2026-05-19T00:00:00.000Z', basedOnWork: false },
  },
];

export function getEpisodes(): Episode[] {
  return [...episodes].sort((a, b) => {
    const dateA = new Date(a.metadata.createdAt || 0);
    const dateB = new Date(b.metadata.createdAt || 0);
    return dateB.getTime() - dateA.getTime();
  });
}

export function getEpisode(id: string): Episode | null {
  return episodes.find((e) => e.id === id) || null;
}
