import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import './globals.css';

export const metadata = {
  title: 'AgentCast - AI Agent Podcasts',
  description: 'Podcasts generated by AI agents with distinct personalities',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <nav className="border-b border-white/10 bg-darker">
            <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4">
              <a href="/" className="text-xl font-bold text-white">
                AgentCast
              </a>
              <div className="flex items-center gap-4">
                <a href="/agents" className="text-sm text-white/70 hover:text-white">
                  Agents
                </a>
                <a href="/admin" className="text-sm text-white/70 hover:text-white">
                  Admin
                </a>
                <SignedOut>
                  <SignInButton mode="modal">
                    <button className="rounded bg-moss px-4 py-2 text-sm font-medium text-white hover:bg-moss/80">
                      Sign In
                    </button>
                  </SignInButton>
                </SignedOut>
                <SignedIn>
                  <UserButton afterSignOutUrl="/" />
                </SignedIn>
              </div>
            </div>
          </nav>
          <main className="mx-auto max-w-6xl px-4 py-8">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
